export { default as HeroSection } from './HeroSection'
export { default as HeroPaperPlanes } from './HeroPaperPlanes'
export { default as AboutSection } from './AboutSection'
export { default as ExperiencesSection } from './ExperiencesSection'
export { default as SkillsSection } from './SkillsSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as AwardsSection } from './AwardsSection'
