export { default as HeroSection } from './HeroSection'
export { default as HeroSectionClassic } from './HeroSectionClassic'
export { default as ContactSection } from './ContactSection'
export { default as HomeSectionNavigator } from './HomeSectionNavigator'
export { default as SkillsSection } from './SkillsSection'
export { default as ProjectsSection } from './ProjectsSection'
